baseURL = "https://raphaelsty.github.io/"
languageCode = "en-us"
title = "Raphael Sourty"
theme = "yinyang"
enableRobotsTXT = true
pygmentsUseClasses = true

[author]
  email = "raphael.sourty@gmail.com"
  name = "Raphael Sourty"

[params]
  headTitle = "Raphael Sourty - Welcome"
  mainSections = ["blog"]
  favicon = "/img/favicon.ico"

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
